### ISSUE TITLE
All data lost when using disc space ran out

### ISSUE THREAD

**Issue by sander2** [hardliner66/timetracking#11]
I just lost all my data after doing a `tt start` when my disk was full. Ideally it would give an error, but leave the existing data file intact.

**Comment by hardliner66** [comment]
Currently tt just overwrites the existing file if something has changed and than unwrap is called on the result. I would expect the unwrap to at least show an error when something like that happens. I need to check how we can prevent the file from corrupting in this scenario.

@sander2 What os and file system were you using when this happened?

**Comment by hardliner66** [comment]
I changed it from directly writing to the file, to writing to a secondary file and replacing the original only if the write succeeds. I also switched from using `std::fs::write` to using `File` directly. This way I can manually call flush, which should get errors that would be hidden by using `std::fs::write`.
